### ISSUE TITLE
Add 'Comment Template' to comment logic block.

### ISSUE THREAD

**Issue by Minku-Koo** [visualpython/visualpython#155]
Add **'Comment Template'** to comment logic block.

_[Original]_
- Only comment beginning with # is provided.

_[Improved]_
- Provides **'comment template'** functionality applicable to Python Class and Method.
- You can add a new template easily.
- **'Comment Templates'** are referenced in the **Numpy Style Guide**.
- [Reference Document 1](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html#example-numpy-style-python-docstrings)
- [Reference Document 2](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard)

_Why Numpy Style Guide?_
- Visual Python has many features for Data Analysis and Machine Learning.
- The Numpy Library is most often used in Data Analysis and ML.

A new function is included in .gif image.

![comment_template_clip](https://user-images.githubusercontent.com/25974226/182367798-fbee1e41-d785-40e7-a545-96bed40e038c.gif)

I want feedback.

thank you.

**Comment by minjk-bl** [comment]
Hello @Minku-Koo ,
Thank you for suggesting your idea. It would be great if it is applied to our project.
I'll wait for your pull-request to apply this idea.

**Comment by minjk-bl** [comment]
`oss_library` branch is not matching with the current structure, so it would be great if you can make PR in the **`devops`** branch!

* `release` branch is only used for releasing new version. For developing purpose, you can use `devops` branch to create pull-request.
