### ISSUE TITLE
#jupyter lab support

### ISSUE THREAD

**Issue by ccfdfvapour** [visualpython/visualpython#174]
现在支持jupyter lab了吗

**Comment by minjk-bl** [comment]
Hello ccfdfvapour :)
Jupyter lab version is not supported yet. We are planning to work on jupyter lab extension very soon.
If there's an update related to jupyter lab, I'll let you know.
Thanks!

**Comment by minjk-bl** [comment]
Hello @ccfdfvapour ,
Visual Python is finally available on Jupyter Lab!
To install Visual Python, use pip command as below.
`pip install jupyterlab-visualpython`

For more information, please refer to Installation page on visualpython.ai.
Here is the [LINK](https://visualpython.ai/installation#jupyterlab)

Thanks!
