### ISSUE TITLE
Add 'tsv' file on File.js options

### ISSUE THREAD

**Issue by Minku-Koo** [visualpython/visualpython#175]
In data analysis, tsv files are frequently used.

Visual Python can not load the tsv file.

I want to add tsv option to this.

![oss2](https://user-images.githubusercontent.com/25974226/187457475-2751cccf-f40d-46e1-845b-294e791440f8.PNG)

**Comment by minjk-bl** [comment]
If read_csv function is used for loading csv and tsv file, I think that `File Type > csv` type need to cover tsv file.
FileNavigation component allows multiple extension types, so it'll be easy to edit `File app > read_csv function` to include tsv extension.
Let us know if you are working on this issue. Thanks :)

**Comment by Minku-Koo** [comment]
yes i am working on this issue.

Then I won't add tsv to select options.

How about selecting csv options, so that can load tsv file?

**Comment by minjk-bl** [comment]
Great, I agree with it.
After selecting csv option, FileNavigation just need to show both csv and tsv files.

**Comment by minjk-bl** [comment]
This issue is solved on version 2.5.0. I'm closing this issue.
