### ISSUE TITLE
[BUG] Error when reading Excel File in VP Note

### ISSUE THREAD

**Issue by jinu0137** [visualpython/visualpython#178]
## Describe the bug
After reading an excel file through Read File in Visual Python, when Run is executed in VP Note, the File Type is operated as csv instead of excel.

### 1. Data Analysis > File > Read File > Select excel as the file type

![image](https://user-images.githubusercontent.com/68031450/190430624-5b65c939-8e16-4fe2-8093-bbb9dd113fa0.png)

### 2. Click the Run button

![image](https://user-images.githubusercontent.com/68031450/190431527-a6ba5050-ec3a-4403-9874-f65208aac427.png)

### 3. See error

![image](https://user-images.githubusercontent.com/68031450/190431916-43f7222d-99ea-4745-a41a-233dc81e800b.png)

## Expected behavior:
Read the Excel file and print the result.

## Desktop:
 - OS: Windows10/11, Mac
 - Browser: Chrome

## VisualPython Information:
 - Version 2.2.12

**Comment by PSP23SCM98D** [comment]
@jinu0137  I could see that this is working fine,Please let me know if the problem still exists.

**Comment by minjk-bl** [comment]
It seems working fine. I'm closing this issue.
