### ISSUE TITLE
[BUG] Unable to read file/To file in Library

### ISSUE THREAD

**Issue by jinu0137** [visualpython/visualpython#180]
## Describe the bug

Read file/To file cannot be performed because Additional Options is not displayed.

### 1. Library > Pandas > Input/Output > Read file/To file

![image](https://user-images.githubusercontent.com/68031450/190859712-fb100e4c-c514-4ae7-906a-84829b1211b1.png)

### 2. See error : Unable to select data.

![image](https://user-images.githubusercontent.com/68031450/190859765-a1fd3de8-3f4c-4b1c-bbd3-315657fe3903.png)

## Expected behavior:
Output the same results as Data Analysis > File > Read File/To File.

## Desktop:
 - OS: Windows10/11, Mac
 - Browser: Chrome

## VisualPython Information:
 - Version 2.2.12 / 2.2.8

**Comment by bharath996** [comment]
I’m also facing the similar error. 

How do you resolve the issue??

**Comment by minjk-bl** [comment]
This bug solved on version 2.3.2, so I'm closing this issue. Thanks :)
