### ISSUE TITLE
Suggestions for Data Analysis > File App > Read File/Write File

### ISSUE THREAD

**Issue by jinlee1703** [visualpython/visualpython#183]
### Purpose

I would like to suggest adding a function that users often use to the File App of Data Analysis.

### Approach

![스크린샷](https://user-images.githubusercontent.com/68031450/191780459-1fe7ac84-69e9-4564-a09f-00766588a29f.png)

---

### 1. I would appreciate it if you could also support me to select a text file (.txt) for File Type in Read File and Write File.

![image](https://user-images.githubusercontent.com/68031450/191781143-d5c1d199-6cdc-4fc0-b2c5-99f42e4846ba.png)

-  Currently, we have selected File Type as csv and modified the path, filename, and extension to resolve the issue.

### 2. In Read File, it would be nice to add the rows option to Additional Options (the option to import only a specified number of rows).

![image](https://user-images.githubusercontent.com/68031450/191782122-4575a28b-38c7-4084-9588-d67c752d385d.png)

### 3. If you selected File Type as excel in Read File, it would be nice to add index_col option to Additional Options.

**If File Type is selected as csv**

![스크린샷](https://user-images.githubusercontent.com/68031450/191782580-c0b9c073-71f7-4d82-a49b-e5983345710c.png)

**If File Type is selected as excel**

![image](https://user-images.githubusercontent.com/68031450/191782753-52408fd5-b2ed-4f03-adc7-af5257b767d6.png)

- Currently, the index_col option is supported only when File Type is set to csv.

**Comment by minjk-bl** [comment]
Solved.
