### ISSUE TITLE
Suggests a help button for the description of the app

### ISSUE THREAD

**Issue by gani0325** [visualpython/visualpython#185]
**Is your feature request related to a problem? Please describe.**
Users may not know how to use the app.

**Describe the solution you'd like**
Create a button to display an app's help description.

**Describe alternatives you've considered**
1. Write the help description you want to add in data/help_data.json.
![image](https://user-images.githubusercontent.com/76983526/192105239-c27a6c20-a0d1-44c5-ad99-ada758f340fe.png)

2.  Apps that don't need help description don't create buttons by boolean.
![image](https://user-images.githubusercontent.com/76983526/192105287-e85439b5-0a02-4052-a0f5-eadff92a963b.png)

3.  Made with markdown version, not codemirror of python code version.
![image](https://user-images.githubusercontent.com/76983526/192105314-68a7bc41-7f7d-4f9c-99d6-a30159f5cbbb.png)
+ In addition, create helpconfig to read the above.
![image](https://user-images.githubusercontent.com/76983526/192105344-dd8a5eae-62d5-44ff-b00a-5728f1ecff88.png)

4.  Hide other buttons so that only one popup appears (not overlapping) when a button is clicked.
![image](https://user-images.githubusercontent.com/76983526/192105364-912b215f-553d-4de7-9e8f-231482e3041f.png)

5. Result
![image](https://user-images.githubusercontent.com/76983526/192105383-ae3f5a09-5272-49f2-8494-f8dcd77b7bcf.png)
![image](https://user-images.githubusercontent.com/76983526/192105393-eedb1791-fe9b-4e72-80f0-d52b92f5e21e.png)

**Comment by minjk-bl** [comment]
Hello @gani0325 ,

Help button could be useful for users, but we have no plan to apply it yet.
Instead, we'll add help button connected to user manual on [gitbook](https://visual-python.gitbook.io/docs/getting-started/welcome-to-visual-python). So this could be an alternative to your suggestion.

Thanks for your idea! :)
