### ISSUE TITLE
[BUG] There is a spelling error on the GitBook page regarding the installation of JupyterLab.

### ISSUE THREAD

**Issue by fantasyma** [visualpython/visualpython#212]
![image](https://user-images.githubusercontent.com/5351410/231167661-dc4e6605-85e8-477c-bf1f-38c9706da349.png)

https://visual-python.gitbook.io/docs/getting-started/how-to-install

pip install juptyerlab-visualpython
jupyter was misspelled as juptyer.It caused my installation to fail

**Comment by minjk-bl** [comment]
We've changed the installation command. Thank you for letting us know!
