### ISSUE TITLE
I don't see an icon on Jupyter lab's right hand side after pip installing and Alteryx Python tool

### ISSUE THREAD

**Issue by nyck33** [visualpython/visualpython#226]
Can you add a screenshot to your instructions/readme?

![image](https://github.com/visualpython/visualpython/assets/25189545/25eef1ed-ef99-4cad-b1ba-8e4a418cd20b)

Where is it?

I opened a second notebook and it was nowhere either.

**Comment by nyck33** [comment]
Also, should this work in Alteryx Python tool?

![image](https://github.com/visualpython/visualpython/assets/25189545/012ffac0-1457-4451-a614-a5edb0f97c32)

I installed both versions but again don't see an orange icon.

**Comment by minjk-bl** [comment]
Hello @nyck33.

1. 
After installation, you have to **refresh the browser**, but if you already refreshed the browser, then we need more information about the situation. Please follow the steps below.
> 1) Press F12 to open the developers tool.
> 2) Open 'Console' tab and take a screenshot. We need this log to find out what is going on behind the screen.
> 3) Please upload the screenshot as a reply.
Also, we're going to upload the screenshot to the instructions as soon as possible. Thank you for the suggestion :)

2. 
Visual Python is the frontend-extension for **Jupyter environment(JupyterLab, JupyterNotebook, JupyterLite) and Colab.**
Unfortunately, we are not supporting the extension for Alteryx Python tool. For now, we don't have plan to support Alteryx Python tool.

**Comment by nyck33** [comment]
@minjk-bl  thanks!  Refreshing the browser worked!
