### ISSUE TITLE
Need some tooltips with hints or links to official pandas documentations for pandas take

### ISSUE THREAD

**Issue by nyck33** [visualpython/visualpython#228]
![image](https://github.com/visualpython/visualpython/assets/25189545/09ccef5b-afa5-4e95-b907-e75d1303e3ca)

I had to look in the documentation to figure out that the Search Index takes a Python list, not just integers nor comma separated integers.

**Comment by minjk-bl** [comment]
Hello @nyck33,

We're now planning to add 'Help' button sequantially for all apps. 
It will take some time, so plz wait for us to complete this update :). 

For now, you can access to pandas documentation page through clicking the information button. 
Plz refer to the screenshot below.
> ![image](https://github.com/visualpython/visualpython/assets/83636412/9d339d63-a5e5-4790-8771-b4b9c3663ac8)
This button will redirect you to the pandas api document page. ([pandas api docs](https://pandas.pydata.org/docs/reference/index.html))

I hope this can helps, thanks.
