### ISSUE TITLE
Suggest : Creating a RESET button instead of a Cancel button

### ISSUE THREAD

**Issue by Minku-Koo** [visualpython/visualpython#232]
I felt the **need for a RESET button** in two situations.

1) Initialize all the data I entered
2) If an error occurs after running the app, and I want to modify form of app from the previous input data

Cancel button and the X button already have the same function.

_So I suggest_

- Create a RESET button instead of the CANCEL button

- After app running, **previously entered data is stored**. Every running, each app

- I can clear all the data with the RESET button, and use the X button instead of the CANCEL button

**Comment by minjk-bl** [comment]
Hello @Minku-Koo ,

For editing previous data, you can use VP Note block. 
After running each app, it automatically save its data on VP Note.

![image](https://github.com/visualpython/visualpython/assets/83636412/8a11adae-98eb-47f9-b773-5ae5ef60add1)

And we recommend to close and open app to reset its data.
Thank you for the suggestion!

**Comment by Minku-Koo** [comment]
Oh I miss that function. 

That is good idea better than me.

Thank you for your feedback.

I will suggest another function for VP, and close this issue.
