### ISSUE TITLE
Suggest : Using parquet and pyArrow, when R/W files

### ISSUE THREAD

**Issue by Minku-Koo** [visualpython/visualpython#233]
How about using parquet and pyArrow, when read and write files?

Starting with pandas 2.0, using pyArrow reduces file reading time.
Also parquet data type is better performance than pickle.

[Reference 1](https://medium.com/@santiagobasulto/pandas-2-0-performance-comparison-3f56b4719f58)
[Reference 2](https://towardsdatascience.com/the-best-format-to-save-pandas-data-414dca023e0d)

So I suggest that add new data type(parquet), and new data read functions(pyArrow) **at File App.**

Thank you

**Comment by minjk-bl** [comment]
Hello @Minku-Koo
I appreciate your suggestion for the file read and write feature using parquet and pyArrow. It sounds like a valuable addition to our project. 

However, we have some higher-priority tasks in progress, which might delay the implementation of this feature. 😢 
Is it possible to support us with development assistance for implementing this feature? Even a minor modification to the File app would be appreciated, or providing the necessary Python code that needs to be created would also be great.

Even if it's not feasible, we will include this suggestion in the to-do list for future releases. 
Thanks!

**Comment by Minku-Koo** [comment]
Hello @minjk-bl 

File input/output App
- Parquet format support
- Pyarrow method support
Content of implementation these functions. 

## 1)
Added pyarrow to Import app.
![image](https://github.com/visualpython/visualpython/assets/25974226/9bf31a13-1264-41af-ad00-840782991222)

## 2)
The csv, json, and parquet formats supported by pyarrow in the File app made it possible to read using pyarrow.

[PyArrow Document (Tabular File Formats)](https://arrow.apache.org/docs/python/api/formats.html)

At this time, you can choose between pandas and pyarrow,
If you select pyarrow, the option area disappears and you can Read File as pyarrow.

like this
pa.csv.read_csv().to_pandas()
pa.json.read_json().to_pandas()

![image](https://github.com/visualpython/visualpython/assets/25974226/c0375809-bc70-45c6-8c99-2ecec34ce72a)


## The way I thought 
In fact, it is possible to add option at file type select box
like this
'csv with pandas'
'csv with pyarrow'

but I think, there method would be too many options needs.


### Please give me feedback.
### Thank you :)

**Comment by minjk-bl** [comment]
Hello @Minku-Koo
There's some ideas to be discussed.
1. It could be better to enable users use 'PyArrow' option with checkbox. Here is the sample what I'm expecting.
![image](https://github.com/visualpython/visualpython/assets/83636412/89f02679-5d33-409b-8af8-a9e816772236)

2. Install / Import option for PyArrow is needed, because it needs additional installation.

Here's brief feedback for your suggestion. It'll be very helpful if this function is added to Visual Python. :)
