### ISSUE TITLE
JupyterLab 4 Support

### ISSUE THREAD

**Issue by MRYingLEE** [visualpython/visualpython#243]
**Is your feature request related to a problem? Please describe.**
It will be great if Visual Python supports JupyterLab 4, which was released about 4 months ago.

**Comment by minjk-bl** [comment]
Hello @MRYingLEE , we are now working on it. So, plz wait until our migration to JupyterLab 4!
I'll let you know when we're ready.
Thanks :)

**Comment by minjk-bl** [comment]
I'm happy to let you know that we're now compatible with JupyterLab 4 and Notebook 7. 😃
You can upgrade Visual Python using pypi.
```
pip install jupyterlab-visualpython==3.0.0
```
Thank you for waiting!
