### ISSUE TITLE
[BUG] Scrolling Issue with iloc in Subset App

### ISSUE THREAD

**Issue by Minku-Koo** [visualpython/visualpython#256]
Hi there,

**To Reproduce**
1. Start the Subset app.
2. Row subset side.
3. Choose iloc for row selection.
4. Scroll down to view additional rows.
5. Observe the scroll behavior.

**Expected behavior**
what you expected to happen

**Desktop (please complete the following information):**
 - OS: Window11
 - Chrome

I've noticed a couple of bugs in the Subset app that need to be addressed. Here are the issues I've identified:

**1. Scrolling Issue in Row Subset Creation with iloc:**
When creating a row subset in the Subset app and selecting iloc, the scroll is indefinitely fixed downwards. This means users are unable to scroll upwards. This behavior disrupts the user experience and needs to be fixed.

**2. Incorrect Number Generation in Scrolling with More Than 10 Rows:**
In the same environment, when the number of rows exceeds 10, scrolling down results in the incorrect generation of new numbers. This inconsistency affects the accuracy of data presentation and should be rectified.

I've resolved these two bugs locally and would like to submit a pull request to address them. Could you please review my changes and let me know if they meet your expectations?

Thank you for your attention to these issues.

**Comment by minjk-bl** [comment]
Hi @Minku-Koo 😄 

Thank you for finding the bug. 
I've just checked the bug you mentioned, and it seems there is indeed an issue. 
We'll incorporate the PR you submitted in the next version and make the necessary updates!

Thank you for your ongoing interest and contributions! 👍🏼
