### ISSUE TITLE
Renewal "Logic" menu design 

### ISSUE THREAD

**Issue by minjk-bl** [visualpython/visualpython#33]
### TO-BE
1.  for, if, elif, while
2. lambda

design reference : 
![image](https://user-images.githubusercontent.com/83636412/120146862-af41d000-c220-11eb-85bd-a7b626839da9.png)
![image](https://user-images.githubusercontent.com/83636412/120146889-be288280-c220-11eb-90be-25ebdb27965e.png)
![image](https://user-images.githubusercontent.com/83636412/120146911-c84a8100-c220-11eb-9bcf-258ace8b2232.png)

--------------------------------

### AS-IS (Optional)
1.

**Comment by visualpython** [comment]
#110
