### ISSUE TITLE
Details from the POV of a newcomer

### ISSUE THREAD

**Issue by set92** [visualpython/visualpython#51]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but some things that, I thought, could be different, or maybe could be helpful to mention as the experience of a newcomer.

- **Too many sections without anything inside**. I suppose you show it to say "VP is going to have all this", but for a newcomer is too much, and is discouraging thinking "Ohh DL code... empty... nvm it has Data analysis WOW... empty... okay, I'm leaving...". I think it would be better for titles to have some mark like WIP, not dhow the empty sections, or maybe a number to show how many operations it has inside, like Boolean operation (9), Linear algebra (6).
    - **Don't use the same color for different things**. Correct me if I'm not right but in the Apps section the gray color means disable, while in the Logic section the gray color doesn't mean that, since continue, break and pass are gray, but I can use them. It confuses me.
- **Not be able to move the interface**. I like to have the menus at the left, but not sure if this is possible. And also the left panel, the one with the Apps and Logic doesn't let me rescale it, but some titles are too long, so I can't see them. An example is "Comparison operations", and yes, I can see it on the tooltip, but I think it would be better to let ppl rescale this panel too.
- **Careful with New note**. I was searching for a way to copy the code that generates VP, and when I clicked the hamburger menu I almost clicked the button of New note, then I tried it and I "lost" all the progress that I made until that moment. Maybe there is a way to recover the last document? Didn't see it, but maybe the solution would be to have tabs instead of replacing old note, or have a message if the previous note has not been saved before.
- **A way to only copy the code**. A preview of all code would be handy too. I wanted to see what code VP generated, not run it, only see how the components were interacting between them. But I didn't find it, at the end I had to use the function to run it with created many cells which then I had to delete, it would have been better to copy all in a cell, and then I would have been able to get the code I wanted, since I was replicating some code that I already have plus adding some section which I didn't know how to program the logic.

Sorry if I was too direct, or I mentioned dumb stuff, I did it intending to help.

**Comment by minjk-bl** [comment]
Hello, set92. 
I read it all carefully, and here I described about problems you got. 

**1. Too many sections without anything inside.**
 - I understand your opinion. On the next release, WIP or some explanation for not implemented operations will be added.
 - Showing a number
**1-1. Don't use the same color for different things**
 - I don't know what is right, but it may confuse some users like you. I'll think about this.

**2. Not be able to move the interface.**
 - It was one of our pending list, but it is not supported yet. maybe after implementing some significant operations, i'll be considered as a feature to update.

**3. Careful with New note.**
 - I think there has to be some comfirm popup before clearing the note.

**4. A way to only copy the code.**
 - For menus except some menus under "Apps", previewing code is provided using preview button on the bottom-right. However, I'm on the same page about just adding code to Jupyter cell is needed. On my own opinion, maybe "Adding Code" menu can be added to block's right click menu.
 
![image](https://user-images.githubusercontent.com/83636412/124572739-d88af700-de83-11eb-9961-2586d08887f1.png)
(somewhere inside here?)

It was so detailed that I could understand well about the situation.
Your interest in VP helps a lot. Thanks. :)

**Comment by minjk-bl** [comment]
Thanks for @set92, visualpython is updated with v1.1.6. 
'Add', 'Preview' function added and some layout has changed.

I will close this issue :)
