### ISSUE TITLE
[BUG] Unable to install

### ISSUE THREAD

**Issue by eurekazheng** [visualpython/visualpython#78]
**Describe the bug**
Files not found while `visualpy install`. Showing:

```
===================================================================================
Not a conda env.

===================================================================================
source : ~10\visualpython\
File not found - visualpython
0 File(s) copied
target : C:\Users\eurekazheng\AppData\Roaming\jupyter\nbextensions\visualpython\
===================================================================================

===================================================================================
Enabling notebook extension visualpython/src/main...
      - Validating: problems found:
        - require?  X visualpython/src/main
===================================================================================
```
Jupyter notebook shows no buttons for visualpython.

**To Reproduce**
1. `conda activate data`
2. `pip install visualpython`
3. `pip install jupyter_contrib_nbextensions` (optional)
4. `visualpy install`

**Expected behavior**
Successfully installed and displays the visualpython button.

**Screenshots**
Not needed.

**Desktop (please complete the following information):**
 - OS: Windows 11 1000.22000.132.0
 - Browser Chrome

**VisualPython Information (please complete the following information):**
 - Version 1.1.7

**Additional context**
Not needed.

**Comment by eurekazheng** [comment]
Thank you Hyewon! That resolved my issue.
For anyone who still experienced the error after this workaround, remember NOT to execute `visualpy install`.

**Comment by llbtl** [comment]
We figure that the problem was different versions of pip. (Visual Python only supports Python version 3.x)
Now we added the _visualpy_ command option for users with multiple Python versions to specify pip version as 3:
```
visualpy install --pip3
```
It will be helpful if you could let us know if you are using a version other than 3. 👀
