### ISSUE TITLE
Support for Jupyter Lab

### ISSUE THREAD

**Issue by eurekazheng** [visualpython/visualpython#80]
Do you plan to support Jupyter Lab? 
It's more useful and probably more popular than notebook now.
And I guess it might not be a very great challenge to adapt to it?

**Comment by Aaron-1974** [comment]
Do you need help translating from Korean to English or English to Korean??

**Comment by llbtl** [comment]
> Do you need help translating from Korean to English or English to Korean??

Hi, Aaron
Did you want to reply to issue #14 ?

We recently translated almost all into English, but since English is not our first language, we still need a check-up for grammar and also wish to improve English expressions for official documents (such as readme and the website).
If you could help us to review existing documents, it would be a big help to us 😃👍🏼 
and thank you for asking !

**Comment by kwon14** [comment]
Thank you for your great work!!
Is support not available in Jupyterlab yet?

**Comment by llbtl** [comment]
> Thank you for your great work!! Is support not available in Jupyterlab yet?

Hi @kwon14, thanks for reminding us about the Jupyterlab. 
We focused more to add & improve functions and currently working on to support Colab first. However, we will definitely support Jupyterlab too. We will get back to you as soon as it is ready. 
Sorry that we missed to share our updated plan! 🙏

**Comment by charmby** [comment]
这个能支持vscode中使用吗？

**Comment by llbtl** [comment]
> 这个能支持vscode中使用吗？

We are planning to support VS Code as an extension to Jupyter Notebook extension but, it may take some time because we are currently working on Colab (Chrome extension) first. Our next steps are as follows : Colab - Jupyter Lab - VS Code. 🙂

**Comment by ccfdfvapour** [comment]
jupyterlab support now？

**Comment by minjk-bl** [comment]
Hello @eurekazheng,

Visual Python is finally available on Jupyter Lab!
To install Visual Python, use pip command as below.
`pip install jupyterlab-visualpython`

For more information, please refer to Installation page on visualpython.ai.
Here is the [LINK](https://visualpython.ai/installation#jupyterlab)

Thanks!

**Comment by Cherkah** [comment]
>  Our next steps are as follows : Colab - Jupyter Lab - VS Code

Now all that’s missing is support for VScode ;)
Maybe this year ?!!

thanks for your work
